# Generated by Django 3.1.7 on 2021-09-14 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ticker',
        ),
    ]
