# Generated by Django 3.1.7 on 2021-09-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210914_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default=models.CharField(default='AAPL', max_length=5), max_length=250),
        ),
        migrations.AddField(
            model_name='stock',
            name='slug',
            field=models.SlugField(default=models.CharField(default='AAPL', max_length=5), max_length=5),
        ),
        migrations.AddField(
            model_name='stock',
            name='ticker',
            field=models.CharField(default='AAPL', max_length=5),
        ),
    ]
