# Generated by Django 3.1.7 on 2021-09-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210914_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(default='Apple', max_length=250),
        ),
        migrations.AlterField(
            model_name='stock',
            name='slug',
            field=models.SlugField(default='AAPL', max_length=5),
        ),
    ]
